name: Workflow Dispatch Merge

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number to Merge into main branch'
        required: true

run-name: Merge PR ${{ github.event.inputs.prNumber }} to main branch

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main # Updated to target the main branch (you can assign any branch of choice for merging)

      - name: Merge Pull Request
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }} # Use your PAT stored in secrets
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          curl -X PUT -H "Authorization: Bearer $PAT_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge"
          echo "Pull Request #$PR_NUMBER has been merged into the main branch."
