name: Notify Slack on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - PR-Approval-with-Emoji

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: PR-Approval-with-Emoji

      - name: Get current time
        id: current-time
        run: echo "::set-output name=time::$(date +%s)"

      - name: Notify Slack - Pull Request Opened
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":eyes: Pull Request Opened",
                  "title": "Pull Request #${{ github.event.pull_request.number }}",
                  "title_link": "${{ github.event.pull_request.html_url }}",
                  "text": "${{ github.event.pull_request.title }}",
                  "fields": [
                    {
                      "title": "Opened by",
                      "value": "${{ github.event.pull_request.user.login }}",
                      "short": true
                    },
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Target Branch",
                      "value": "${{ github.event.pull_request.base.ref }}",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }