name: Notify Slack on PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main # Updated to target the main branch (you can assign any part of choice for merging)

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main # Updated to target the main branch

      - name: Get current time
        id: current-time
        run: echo "::set-output name=time::$(date +%s)"

      - name: Notify Slack - Pull Request Opened
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#1E90FF",
                  "pretext": ":eyes: Pull Request Opened",
                  "title": "<${{ github.event.pull_request.html_url }}|Pull Request #${{ github.event.pull_request.number }}> from <https://github.com/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}|${{ github.event.pull_request.head.ref }}>",
                  "text": "${{ github.event.pull_request.title }}",
                  "fields": [
                    {
                      "title": "Opened by",
                      "value": "<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>",
                      "short": true
                    },
                    {
                      "title": "Repository",
                      "value": "<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>",
                      "short": true
                    },
                    {
                      "title": "Target Branch",
                      "value": "${{ github.event.pull_request.base.ref }}",
                      "short": true
                    },
                    {
                      "title": "Source Branch",
                      "value": "<https://github.com/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}|${{ github.event.pull_request.head.ref }}>",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }
