name: Pull Request Approval Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL_ID: "C06R1GVVDPF"
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - name: Notify Slack - Pull Request Opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          curl -s -X POST -H 'Content-type: application/json' -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            --data '{"channel":"'"$SLACK_CHANNEL_ID"'","text":":eyes: Pull Request Opened\nPull Request #${{ github.event.pull_request.number }}\n${{ github.event.pull_request.html_url }}"}' \
            https://slack.com/api/chat.postMessage

      - name: Check Pull Request Approvals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all open pull requests
          pull_requests=$(gh pr list --json number,title,url --state open --limit 100)

          # Loop through each pull request
          for pr in $(echo "$pull_requests" | jq -c '.[]'); do
            pr_number=$(echo "$pr" | jq -r '.number')
            pr_title=$(echo "$pr" | jq -r '.title')
            pr_url=$(echo "$pr" | jq -r '.url')

            # Find the latest 'Pull Request Opened' message for the current PR
            message_id=$(curl -s -H "Authorization: Bearer $SLACK_BOT_TOKEN" "https://slack.com/api/conversations.history?channel=$SLACK_CHANNEL_ID&limit=100" | jq -r ".messages | map(select(.text | contains(\"Pull Request #$pr_number\"))) | .[0].ts")

            if [ -n "$message_id" ]; then
              # Get the count of thumbs-up reactions for the message
              reaction_count=$(curl -s -H "Authorization: Bearer $SLACK_BOT_TOKEN" "https://slack.com/api/reactions.get?channel=$SLACK_CHANNEL_ID&timestamp=$message_id" | jq '.message.reactions[] | select(.name=="thumbsup") | .count')

              echo "Pull Request #$pr_number - Thumbs-up count: $reaction_count"

              if [ "$reaction_count" -ge 5 ]; then
                echo "Merging Pull Request #$pr_number"
                gh pr merge "$pr_number" --auto --merge
                echo "Pull Request #$pr_number has been merged to the main branch"
              fi
            else
              echo "No 'Pull Request Opened' message found for Pull Request #$pr_number"
            fi
          done

      - name: Notify Slack - Pull Request Approved and Merged
        if: success()
        run: |
          curl -s -X POST -H 'Content-type: application/json' -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            --data '{"channel":"'"$SLACK_CHANNEL_ID"'","text":":white_check_mark: Pull Request(s) Approved and Merged"}' \
            https://slack.com/api/chat.postMessage