name: Pull Request Approval Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes to check for approvals.

jobs:
  check_approvals_and_merge:
    runs-on: ubuntu-latest
    env:
      SLACK_CHANNEL_ID: C06R1GVVDPF
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install gh -y
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check Pull Request Approvals
        run: |
          # Get all open pull requests
          pull_requests=$(gh pr list --json number --state open --limit 100)
          echo "$pull_requests"
          
          # Loop through each pull request
          for pr_number in $(echo "$pull_requests" | jq -r '.[].number'); do
            echo "Checking PR #$pr_number for approvals"
            
            # Find the latest 'Pull Request Opened' message for the current PR
            message_id=$(curl -s -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              "https://slack.com/api/conversations.history?channel=$SLACK_CHANNEL_ID&limit=100" | \
              jq -r ".messages | map(select(.text | test(\"Pull Request #${pr_number}(\\\\s|:|$)\"))) | .[0].ts // empty")
            
            if [[ -n "$message_id" ]]; then
              # Get the count of thumbs-up reactions for the message
              reaction_count=$(curl -s -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                "https://slack.com/api/reactions.get?channel=$SLACK_CHANNEL_ID&timestamp=$message_id" | \
                jq '.message.reactions[] | select(.name == "+1" or .name == "thumbsup") | .count // 0')
              
              echo "Pull Request #$pr_number - Thumbs-up count: $reaction_count"
              
              if [[ "$reaction_count" -ge 5 ]]; then
                echo "Merging Pull Request #$pr_number with $reaction_count thumbs-up reactions."
                gh pr merge "$pr_number" --auto --merge
              else
                echo "Pull Request #$pr_number has not reached the required number of approvals."
              fi
            else
              echo "No 'Pull Request Opened' message found for Pull Request #$pr_number in Slack."
            fi
          done
