name: Python application with Slack notifications

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Notify Slack - Python Setup
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":python: Python 3.12 has been set up for the workflow."
            }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Notify Slack - Dependencies Installed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":white_check_mark: All dependencies have been successfully installed. Installed ${{ steps.install-dependencies.outputs.installed }}/x dependencies."
            }
      - name: Notify Slack - Dependencies Installation Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":x: Failed to install dependencies."
            }

      - name: Notify Slack on Action
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":rocket: ${{ github.event_name }} event triggered by ${{ github.actor }} on repository ${{ github.repository }} for branch ${{ github.ref }}."
            }

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Notify Slack - Linting Passed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":white_check_mark: Linting passed successfully. All ${{ steps.lint.outputs.total_files }}/x files passed linting."
            }
      - name: Notify Slack - Linting Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":x: Linting failed with errors in ${{ steps.lint.outputs.failed_files }}/y files."
            }

      - name: Check for test files and run pytest if found
        run: |
          if compgen -G "tests/test_*.py" > /dev/null; then
            pytest
          else
            echo "No tests found. Skipping pytest."
          fi
      - name: Notify Slack - Tests Passed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":white_check_mark: All ${{ steps.tests.outputs.passed_tests }}/x tests passed successfully."
            }
      - name: Notify Slack - Tests Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":x: ${{ steps.tests.outputs.failed_tests }}/y tests failed."
            }

      - name: Notify Slack - Workflow Succeeded
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":tada: The workflow completed successfully. All steps passed without any errors."
            }
      - name: Notify Slack - Workflow Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": ":x: The workflow failed. Please check the logs for more details."
            }