name: Python application with Enhanced Slack notifications

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          deps_count=$(pip freeze | wc -l)
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          new_deps_count=$(pip freeze | wc -l)
          echo "INSTALLED_DEPENDENCIES=$((new_deps_count - deps_count))" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true

      - name: Run pytest
        id: pytest
        run: pytest || echo "::set-output name=failed::true"

      - name: Compile Notification Message
        id: compile_message
        run: |
          message="Action type: ${{ github.event_name }}\n"
          message+="Action Performer: ${{ github.actor }}\n"
          message+="repo name: ${{ github.repository }}\n"
          message+="branch name: ${{ github.ref_name }}\n"
          message+="All dependencies installed: ${{ env.INSTALLED_DEPENDENCIES }} dependencies\n"
          if [ "${{ steps.pytest.outputs.failed }}" == "true" ]; then
            message+="Tests: Some tests failed\n"
          else
            message+="Tests: All tests passed\n"
          fi
          if [ ${{ job.status }} == "success" ]; then
            message+="Workflow status: succeeded\n"
          else
            message+="Workflow status: failed\n"
          fi
          echo "::set-output name=message::$message"

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "text": "${{ steps.compile_message.outputs.message }}"
            }
