name: backend-python-app staging deployment

on:
  workflow_run:
    workflows: [Workflow Dispatch Merge]
    types:
      - completed
    branches:
      - 'main'

permissions:
  contents: read

run-name: Deploy staging app to ${{ inputs.deploy_target }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get current time
        id: current-time
        run: echo "::set-output name=time::$(date +%s)"

      - name: Notify Slack - Preparing Deployment
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":hourglass_flowing_sand: Waiting for merge to main completed. Deploying the app to Heroku...",
                  "title": "Deployment Preparation",
                  "text": "The merge to the main branch has completed successfully. Now preparing to deploy the app to Heroku.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v3

      - name: Notify Slack on Action
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":rocket: ${{ github.event_name }} event triggered",
                  "title": "${{ github.repository }}",
                  "text": "Triggered by ${{ github.actor }} on branch ${{ github.ref_name }}",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Notify Slack - Python Setup
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":python: Python 3.12 has been set up",
                  "title": "Python Setup",
                  "text": "Python 3.12 has been successfully set up for the workflow.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        id: install-dependencies

      - name: Notify Slack - Dependencies Installed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":white_check_mark: Dependencies installed",
                  "title": "Dependency Installation",
                  "text": "All dependencies have been successfully installed.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Notify Slack - Dependencies Installation Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000",
                  "pretext": ":x: Dependencies installation failed",
                  "title": "Dependency Installation",
                  "text": "Failed to install dependencies. Please check the logs for more details.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        id: lint

      - name: Notify Slack - Linting Passed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":white_check_mark: Linting passed",
                  "title": "Linting",
                  "text": "Linting passed successfully.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Notify Slack - Linting Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000",
                  "pretext": ":x: Linting failed",
                  "title": "Linting",
                  "text": "Linting failed with errors. Please check the logs for more details.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Check for test files and run pytest if found
        run: |
          if compgen -G "tests/test_*.py" > /dev/null; then
            pytest
          else
            echo "No tests found. Skipping pytest."
          fi
        id: tests

      - name: Notify Slack - Tests Passed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":white_check_mark: Tests passed",
                  "title": "Testing",
                  "text": "All tests passed successfully.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Notify Slack - Tests Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000",
                  "pretext": ":x: Tests failed",
                  "title": "Testing",
                  "text": "Tests failed. Please check the logs for more details.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Notify Slack - Deployment
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":rocket: Deployment completed",
                  "title": "Deployment",
                  "text": "The application has been successfully deployed.",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    },
                    {
                      "title": "Deployed by",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Completed",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Notify Slack - Workflow Succeeded
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":tada: Workflow completed successfully",
                  "title": "Workflow",
                  "text": "The workflow completed successfully. All steps passed without any errors.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }

      - name: Notify Slack - Workflow Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000",
                  "pretext": ":x: Workflow failed",
                  "title": "Workflow",
                  "text": "The workflow failed. Please check the logs for more details.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": ${{ steps.current-time.outputs.time }}
                }
              ]
            }
      
