name: Workflow Dispatch Merge

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number to Merge into main Branch'
        required: true

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check Workflows Status
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          REPO_NAME="${{ github.repository }}"
          WORKFLOW_RUNS=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_NAME/actions/runs?event=pull_request&branch=main")
          
          # Wait for all required workflows to complete successfully
          REQUIRED_WORKFLOWS=("CodeQL") # Add the names of the required workflows
          for WORKFLOW_NAME in "${REQUIRED_WORKFLOWS[@]}"; do
            RUN_ID=$(echo $WORKFLOW_RUNS | jq -r '.workflow_runs[] | select(.name == "'$WORKFLOW_NAME'" and .head_branch == "PR-'$PR_NUMBER'") | .id')
            if [ -z "$RUN_ID" ]; then
              echo "Workflow run for $WORKFLOW_NAME not found for PR #$PR_NUMBER."
              exit 1
            fi
            
            STATUS="queued"
            while [[ "$STATUS" == "queued" || "$STATUS" == "in_progress" ]]; do
              sleep 15
              RUN_STATUS=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO_NAME/actions/runs/$RUN_ID")
              STATUS=$(echo $RUN_STATUS | jq -r '.status')
              CONCLUSION=$(echo $RUN_STATUS | jq -r '.conclusion')
            done
            
            if [ "$CONCLUSION" != "success" ]; then
              echo "Workflow $WORKFLOW_NAME did not complete successfully for PR #$PR_NUMBER."
              exit 1
            fi
          done
          
          echo "All required workflows completed successfully for PR #$PR_NUMBER."

      - name: Merge Pull Request
        if: steps.check_status.conclusion == 'success'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          curl -X PUT -H "Authorization: Bearer $PAT_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
          -d '{"merge_method":"squash"}'
          echo "Pull Request #$PR_NUMBER has been merged into the main branch."