name: Workflow Dispatch Merge

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number to Merge into main Branch'
        required: true

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check Workflows Status
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          REPO_NAME="${{ github.repository }}"
          PR_BRANCH=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER" | jq -r '.head.ref')
          
          echo "PR_BRANCH: $PR_BRANCH"
          if [ -z "$PR_BRANCH" ]; then
            echo "Pull Request #$PR_NUMBER not found in the repository."
            exit 1
          fi
          
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_NAME/actions/runs?event=pull_request&branch=$PR_BRANCH")
          
          REQUIRED_WORKFLOWS=("CodeQL") # Add other workflow names here if necessary
          for WORKFLOW_NAME in "${REQUIRED_WORKFLOWS[@]}"; do
            echo "Checking workflow: $WORKFLOW_NAME"
            RUN_ID=$(echo $WORKFLOW_RUNS | jq -r --arg WORKFLOW_NAME "$WORKFLOW_NAME" '.workflow_runs[] | select(.name == $WORKFLOW_NAME) | .id')
            echo "RUN_ID for $WORKFLOW_NAME: $RUN_ID"
            if [ -z "$RUN_ID" ]; then
              echo "Workflow run for $WORKFLOW_NAME not found for PR #$PR_NUMBER on branch $PR_BRANCH."
              exit 1
            fi
            
            STATUS="queued"
            while [[ "$STATUS" == "queued" || "$STATUS" == "in_progress" ]]; do
              sleep 15
              RUN_STATUS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO_NAME/actions/runs/$RUN_ID")
              STATUS=$(echo $RUN_STATUS | jq -r '.status')
              CONCLUSION=$(echo $RUN_STATUS | jq -r '.conclusion')
              
              if [[ "$STATUS" == "completed" && "$CONCLUSION" != "success" ]]; then
                echo "Workflow $WORKFLOW_NAME did not complete successfully for PR #$PR_NUMBER."
                exit 1
              fi
            done
          done
          echo "All required workflows completed successfully for PR #$PR_NUMBER."

      - name: Merge Pull Request
        if: ${{ success() }}
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          curl -X PUT -H "Authorization: Bearer $PAT_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
          -d '{"merge_method":"squash"}'
          echo "Pull Request #$PR_NUMBER has been merged into the main branch."
