name: Workflow Dispatch Merge

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number to Merge into main Branch'
        required: true

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check Workflows Status
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This can be a PAT as well
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          REPO_NAME="${{ github.repository }}"
          WORKFLOW_RUNS=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_NAME/actions/runs?event=pull_request&branch=main")
          # Assuming you have a specific workflow you want to check, like "CI Workflow"
          # Adjust the jq filter path according to your workflow's name
          RUN_ID=$(echo $WORKFLOW_RUNS | jq -r '.workflow_runs[] | select(.name == "CI Workflow" and .head_branch == "PR-'$PR_NUMBER'") | .id')
          if [ -z "$RUN_ID" ]; then
            echo "Workflow run for PR #$PR_NUMBER not found."
            exit 1
          fi

          # Poll the API to wait for the workflow run to complete
          STATUS="queued"
          while [[ "$STATUS" == "queued" || "$STATUS" == "in_progress" ]]; do
            sleep 15
            RUN_STATUS=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO_NAME/actions/runs/$RUN_ID")
            STATUS=$(echo $RUN_STATUS | jq -r '.status')
            CONCLUSION=$(echo $RUN_STATUS | jq -r '.conclusion')
          done

          if [ "$CONCLUSION" != "success" ]; then
            echo "Workflow did not complete successfully."
            exit 1
          fi

      - name: Merge Pull Request
        if: steps.check_status.conclusion == 'success'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.inputs.prNumber }}
          curl -X PUT -H "Authorization: Bearer $PAT_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
          -d '{"merge_method":"squash"}' # Adjust merge method as needed
          echo "Pull Request #$PR_NUMBER has been merged into the main branch."
